// Generic

export const DATA_GET_REQ = 'DATA_GET_REQ';
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS';
export const DATA_GET_ERROR = 'DATA_GET_ERROR';

export const DATA_PUT_REQ = 'DATA_PUT_REQ';
export const DATA_PUT_SUCCESS = 'DATA_PUT_SUCCESS';
export const DATA_PUT_ERROR = 'DATA_PUT_ERROR';

export const DATA_POST_REQ = 'DATA_POST_REQ';
export const DATA_POST_SUCCESS = 'DATA_POST_SUCCESS';
export const DATA_POST_ERROR = 'DATA_POST_ERROR';

// Super Admin Panel

export const TOWNSHIP_FETCH_GET_REQ = 'TOWNSHIP_FETCH_GET_REQ';
export const TOWNSHIP_FETCH_GET_SUCCESS = 'TOWNSHIP_FETCH_GET_SUCCESS';
export const TOWNSHIP_FETCH_GET_ERROR = 'TOWNSHIP_FETCH_GET_ERROR';

export const DETAILS_FETCH_GET_REQ = 'DETAILS_FETCH_GET_REQ';
export const DETAILS_FETCH_GET_SUCCESS = 'DETAILS_FETCH_GET_SUCCESS';
export const DETAILS_FETCH_GET_ERROR = 'DETAILS_FETCH_GET_ERROR';

export const TOWNSHIP_EDIT_PUT_REQ = 'TOWNSHIP_EDIT_PUT_REQ';
export const TOWNSHIP_EDIT_PUT_SUCCESS = 'TOWNSHIP_EDIT_PUT_SUCCESS';
export const TOWNSHIP_EDIT_PUT_ERROR = 'TOWNSHIP_EDIT_PUT_ERROR';

export const TOWNSHIP_IMAGE_PUT_REQ = 'TOWNSHIP_IMAGE_PUT_REQ';
export const TOWNSHIP_IMAGE_PUT_SUCCESS = 'TOWNSHIP_IMAGE_PUT_SUCCESS';
export const TOWNSHIP_IMAGE_PUT_ERROR = 'TOWNSHIP_IMAGE_PUT_ERROR';

export const TOWNSHIP_CREATE_POST_REQ = 'TOWNSHIP_CREATE_POST_REQ';
export const TOWNSHIP_CREATE_POST_SUCCESS = 'TOWNSHIP_CREATE_POST_SUCCESS';
export const TOWNSHIP_CREATE_POST_ERROR = 'TOWNSHIP_CREATE_POST_ERROR';

export const UPLOAD_TOWNSHIP_IMAGE_REQ = 'UPLOAD_TOWNSHIP_IMAGE_REQ';
export const UPLOAD_TOWNSHIP_IMAGE_SUCCESS = 'UPLOAD_TOWNSHIP_IMAGE_SUCCESS';
export const UPLOAD_TOWNSHIP_IMAGE_ERROR = 'UPLOAD_TOWNSHIP_IMAGE_ERROR';

// Township Common

export const RESET_LOADING = 'RESET_LOADING';

export const TOWNSHIP_SCHEME_TYPES_GET_REQ = 'TOWNSHIP_SCHEME_TYPES_GET_REQ';
export const TOWNSHIP_SCHEME_TYPES_GET_SUCCESS = 'TOWNSHIP_SCHEME_TYPES_GET_SUCCESS';
export const TOWNSHIP_SCHEME_TYPES_GET_ERROR = 'TOWNSHIP_SCHEME_TYPES_GET_ERROR';

// Township Panel

export const TOWNSHIP_USERS_GET_REQ = 'TOWNSHIP_USERS_GET_REQ';
export const TOWNSHIP_USERS_GET_SUCCESS = 'TOWNSHIP_USERS_GET_SUCCESS';
export const TOWNSHIP_USERS_GET_ERROR = 'TOWNSHIP_USERS_GET_ERROR';

export const TOWNSHIP_USERS_PUT_REQ = 'TOWNSHIP_USERS_PUT_REQ';
export const TOWNSHIP_USERS_PUT_SUCCESS = 'TOWNSHIP_USERS_PUT_SUCCESS';
export const TOWNSHIP_USERS_PUT_ERROR = 'TOWNSHIP_USERS_PUT_ERROR';

export const TOWNSHIP_USERS_POST_REQ = 'TOWNSHIP_USERS_POST_REQ';
export const TOWNSHIP_USERS_POST_SUCCESS = 'TOWNSHIP_USERS_POST_SUCCESS';
export const TOWNSHIP_USERS_POST_ERROR = 'TOWNSHIP_USERS_POST_ERROR';

export const TOWNSHIP_FACILITIES_GET_REQ = 'TOWNSHIP_FACILITIES_GET_REQ';
export const TOWNSHIP_FACILITIES_GET_SUCCESS = 'TOWNSHIP_FACILITIES_GET_SUCCESS';
export const TOWNSHIP_FACILITIES_GET_ERROR = 'TOWNSHIP_FACILITIES_GET_ERROR';

export const TOWNSHIP_FACILITIES_PUT_REQ = 'TOWNSHIP_FACILITIES_PUT_REQ';
export const TOWNSHIP_FACILITIES_PUT_SUCCESS = 'TOWNSHIP_FACILITIES_PUT_SUCCESS';
export const TOWNSHIP_FACILITIES_PUT_ERROR = 'TOWNSHIP_FACILITIES_PUT_ERROR';

export const TOWNSHIP_FACILITIES_POST_REQ = 'TOWNSHIP_FACILITIES_POST_REQ';
export const TOWNSHIP_FACILITIES_POST_SUCCESS = 'TOWNSHIP_FACILITIES_POST_SUCCESS';
export const TOWNSHIP_FACILITIES_POST_ERROR = 'TOWNSHIP_FACILITIES_POST_ERROR';



export const TOWNSHIP_LOCATIONS_GET_REQ = 'TOWNSHIP_LOCATIONS_GET_REQ';
export const TOWNSHIP_LOCATIONS_GET_SUCCESS = 'TOWNSHIP_LOCATIONS_GET_SUCCESS';
export const TOWNSHIP_LOCATIONS_GET_ERROR = 'TOWNSHIP_LOCATIONS_GET_ERROR';

export const TOWNSHIP_LOCATIONS_PUT_REQ = 'TOWNSHIP_LOCATIONS_PUT_REQ';
export const TOWNSHIP_LOCATIONS_PUT_SUCCESS = 'TOWNSHIP_LOCATIONS_PUT_SUCCESS';
export const TOWNSHIP_LOCATIONS_PUT_ERROR = 'TOWNSHIP_LOCATIONS_PUT_ERROR';

export const TOWNSHIP_LOCATIONS_POST_REQ = 'TOWNSHIP_LOCATIONS_POST_REQ';
export const TOWNSHIP_LOCATIONS_POST_SUCCESS = 'TOWNSHIP_LOCATIONS_POST_SUCCESS';
export const TOWNSHIP_LOCATIONS_POST_ERROR = 'TOWNSHIP_LOCATIONS_POST_ERROR';



export const TOWNSHIP_PERMITS_GET_REQ = 'TOWNSHIP_PERMITS_GET_REQ';
export const TOWNSHIP_PERMITS_GET_SUCCESS = 'TOWNSHIP_PERMITS_GET_SUCCESS';
export const TOWNSHIP_PERMITS_GET_ERROR = 'TOWNSHIP_PERMITS_GET_ERROR';

export const TOWNSHIP_PERMITS_PUT_REQ = 'TOWNSHIP_PERMITS_PUT_REQ';
export const TOWNSHIP_PERMITS_PUT_SUCCESS = 'TOWNSHIP_PERMITS_PUT_SUCCESS';
export const TOWNSHIP_PERMITS_PUT_ERROR = 'TOWNSHIP_PERMITS_PUT_ERROR';

export const TOWNSHIP_PERMITS_POST_REQ = 'TOWNSHIP_PERMITS_POST_REQ';
export const TOWNSHIP_PERMITS_POST_SUCCESS = 'TOWNSHIP_PERMITS_POST_SUCCESS';
export const TOWNSHIP_PERMITS_POST_ERROR = 'TOWNSHIP_PERMITS_POST_ERROR';



export const TOWNSHIP_PERMIT_REQUESTS_GET_REQ = 'TOWNSHIP_PERMIT_REQUESTS_GET_REQ';
export const TOWNSHIP_PERMIT_REQUESTS_GET_SUCCESS = 'TOWNSHIP_PERMIT_REQUESTS_GET_SUCCESS';
export const TOWNSHIP_PERMIT_REQUESTS_GET_ERROR = 'TOWNSHIP_PERMIT_REQUESTS_GET_ERROR';

export const TOWNSHIP_PERMIT_REQUESTS_PUT_REQ = 'TOWNSHIP_PERMIT_REQUESTS_PUT_REQ';
export const TOWNSHIP_PERMIT_REQUESTS_PUT_SUCCESS = 'TOWNSHIP_PERMIT_REQUESTS_PUT_SUCCESS';
export const TOWNSHIP_PERMIT_REQUESTS_PUT_ERROR = 'TOWNSHIP_PERMIT_REQUESTS_PUT_ERROR';

export const TOWNSHIP_PERMIT_REQUESTS_POST_REQ = 'TOWNSHIP_PERMIT_REQUESTS_POST_REQ';
export const TOWNSHIP_PERMIT_REQUESTS_POST_SUCCESS = 'TOWNSHIP_PERMIT_REQUESTS_POST_SUCCESS';
export const TOWNSHIP_PERMIT_REQUESTS_POST_ERROR = 'TOWNSHIP_PERMIT_REQUESTS_POST_ERROR';



export const TOWNSHIP_PERMIT_TYPES_GET_REQ = 'TOWNSHIP_PERMIT_TYPES_GET_REQ';
export const TOWNSHIP_PERMIT_TYPES_GET_SUCCESS = 'TOWNSHIP_PERMIT_TYPES_GET_SUCCESS';
export const TOWNSHIP_PERMIT_TYPES_GET_ERROR = 'TOWNSHIP_PERMIT_TYPES_GET_ERROR';

export const TOWNSHIP_PERMIT_TYPES_PUT_REQ = 'TOWNSHIP_PERMIT_TYPES_PUT_REQ';
export const TOWNSHIP_PERMIT_TYPES_PUT_SUCCESS = 'TOWNSHIP_PERMIT_TYPES_PUT_SUCCESS';
export const TOWNSHIP_PERMIT_TYPES_PUT_ERROR = 'TOWNSHIP_PERMIT_TYPES_PUT_ERROR';

export const TOWNSHIP_PERMIT_TYPES_POST_REQ = 'TOWNSHIP_PERMIT_TYPES_POST_REQ';
export const TOWNSHIP_PERMIT_TYPES_POST_SUCCESS = 'TOWNSHIP_PERMIT_TYPES_POST_SUCCESS';
export const TOWNSHIP_PERMIT_TYPES_POST_ERROR = 'TOWNSHIP_PERMIT_TYPES_POST_ERROR';



export const TOWNSHIP_PERMITS_LIST_GET_REQ = 'TOWNSHIP_PERMITS_LIST_GET_REQ';
export const TOWNSHIP_PERMITS_LIST_GET_SUCCESS = 'TOWNSHIP_PERMITS_LIST_GET_SUCCESS';
export const TOWNSHIP_PERMITS_LIST_GET_ERROR = 'TOWNSHIP_PERMITS_LIST_GET_ERROR';

export const TOWNSHIP_PERMITS_LIST_PUT_REQ = 'TOWNSHIP_PERMITS_LIST_PUT_REQ';
export const TOWNSHIP_PERMITS_LIST_PUT_SUCCESS = 'TOWNSHIP_PERMITS_LIST_PUT_SUCCESS';
export const TOWNSHIP_PERMITS_LIST_PUT_ERROR = 'TOWNSHIP_PERMITS_LIST_PUT_ERROR';

export const TOWNSHIP_PERMITS_LIST_POST_REQ = 'TOWNSHIP_PERMITS_LIST_POST_REQ';
export const TOWNSHIP_PERMITS_LIST_POST_SUCCESS = 'TOWNSHIP_PERMITS_LIST_POST_SUCCESS';
export const TOWNSHIP_PERMITS_LIST_POST_ERROR = 'TOWNSHIP_PERMITS_LIST_POST_ERROR';




export const TOWNSHIP_PARKING_PERMITS_GET_REQ = 'TOWNSHIP_PARKING_PERMITS_GET_REQ';
export const TOWNSHIP_PARKING_PERMITS_GET_SUCCESS = 'TOWNSHIP_PARKING_PERMITS_GET_SUCCESS';
export const TOWNSHIP_PARKING_PERMITS_GET_ERROR = 'TOWNSHIP_PARKING_PERMITS_GET_ERROR';

export const TOWNSHIP_PARKING_PERMITS_PUT_REQ = 'TOWNSHIP_PARKING_PERMITS_PUT_REQ';
export const TOWNSHIP_PARKING_PERMITS_PUT_SUCCESS = 'TOWNSHIP_PARKING_PERMITS_PUT_SUCCESS';
export const TOWNSHIP_PARKING_PERMITS_PUT_ERROR = 'TOWNSHIP_PARKING_PERMITS_PUT_ERROR';

export const TOWNSHIP_PARKING_PERMITS_POST_REQ = 'TOWNSHIP_PARKING_PERMITS_POST_REQ';
export const TOWNSHIP_PARKING_PERMITS_POST_SUCCESS = 'TOWNSHIP_PARKING_PERMITS_POST_SUCCESS';
export const TOWNSHIP_PARKING_PERMITS_POST_ERROR = 'TOWNSHIP_PARKING_PERMITS_POST_ERROR';





export const TOWNSHIP_LOCATIONS_RATE_GET_REQ = 'TOWNSHIP_LOCATIONS_RATE_GET_REQ';
export const TOWNSHIP_LOCATIONS_RATE_GET_SUCCESS = 'TOWNSHIP_LOCATIONS_RATE_GET_SUCCESS';
export const TOWNSHIP_LOCATIONS_RATE_GET_ERROR = 'TOWNSHIP_LOCATIONS_RATE_GET_ERROR';

export const TOWNSHIP_LOCATIONS_RATE_PUT_REQ = 'TOWNSHIP_LOCATIONS_RATE_PUT_REQ';
export const TOWNSHIP_LOCATIONS_RATE_PUT_SUCCESS = 'TOWNSHIP_LOCATIONS_RATE_PUT_SUCCESS';
export const TOWNSHIP_LOCATIONS_RATE_PUT_ERROR = 'TOWNSHIP_LOCATIONS_RATE_PUT_ERROR';

export const TOWNSHIP_LOCATIONS_RATE_POST_REQ = 'TOWNSHIP_LOCATIONS_RATE_POST_REQ';
export const TOWNSHIP_LOCATIONS_RATE_POST_SUCCESS = 'TOWNSHIP_LOCATIONS_RATE_POST_SUCCESS';
export const TOWNSHIP_LOCATIONS_RATE_POST_ERROR = 'TOWNSHIP_LOCATIONS_RATE_POST_ERROR';


export const TOWNSHIP_PARKING_RULES_GET_REQ = 'TOWNSHIP_PARKING_RULES_GET_REQ';
export const TOWNSHIP_PARKING_RULES_GET_SUCCESS = 'TOWNSHIP_PARKING_RULES_GET_SUCCESS';
export const TOWNSHIP_PARKING_RULES_GET_ERROR = 'TOWNSHIP_PARKING_RULES_GET_ERROR';

export const TOWNSHIP_PARKING_RULES_PUT_REQ = 'TOWNSHIP_PARKING_RULES_PUT_REQ';
export const TOWNSHIP_PARKING_RULES_PUT_SUCCESS = 'TOWNSHIP_PARKING_RULES_PUT_SUCCESS';
export const TOWNSHIP_PARKING_RULES_PUT_ERROR = 'TOWNSHIP_PARKING_RULES_PUT_ERROR';

export const TOWNSHIP_PARKING_RULES_POST_REQ = 'TOWNSHIP_PARKING_RULES_POST_REQ';
export const TOWNSHIP_PARKING_RULES_POST_SUCCESS = 'TOWNSHIP_PARKING_RULES_POST_SUCCESS';
export const TOWNSHIP_PARKING_RULES_POST_ERROR = 'TOWNSHIP_PARKING_RULES_POST_ERROR';





export const TOWNSHIP_VIOLATION_CODE_GET_REQ = 'TOWNSHIP_VIOLATION_CODE_GET_REQ';
export const TOWNSHIP_VIOLATION_CODE_GET_SUCCESS = 'TOWNSHIP_VIOLATION_CODE_GET_SUCCESS';
export const TOWNSHIP_VIOLATION_CODE_GET_ERROR = 'TOWNSHIP_VIOLATION_CODE_GET_ERROR';

export const TOWNSHIP_VIOLATION_CODE_PUT_REQ = 'TOWNSHIP_VIOLATION_CODE_PUT_REQ';
export const TOWNSHIP_VIOLATION_CODE_PUT_SUCCESS = 'TOWNSHIP_VIOLATION_CODE_PUT_SUCCESS';
export const TOWNSHIP_VIOLATION_CODE_PUT_ERROR = 'TOWNSHIP_VIOLATION_CODE_PUT_ERROR';

export const TOWNSHIP_VIOLATION_CODE_POST_REQ = 'TOWNSHIP_VIOLATION_CODE_POST_REQ';
export const TOWNSHIP_VIOLATION_CODE_POST_SUCCESS = 'TOWNSHIP_VIOLATION_CODE_POST_SUCCESS';
export const TOWNSHIP_VIOLATION_CODE_POST_ERROR = 'TOWNSHIP_VIOLATION_CODE_POST_ERROR';





export const TOWNSHIP_HEARING_PLACE_GET_REQ = 'TOWNSHIP_HEARING_PLACE_GET_REQ';
export const TOWNSHIP_HEARING_PLACE_GET_SUCCESS = 'TOWNSHIP_HEARING_PLACE_GET_SUCCESS';
export const TOWNSHIP_HEARING_PLACE_GET_ERROR = 'TOWNSHIP_HEARING_PLACE_GET_ERROR';

export const TOWNSHIP_HEARING_PLACE_PUT_REQ = 'TOWNSHIP_HEARING_PLACE_PUT_REQ';
export const TOWNSHIP_HEARING_PLACE_PUT_SUCCESS = 'TOWNSHIP_HEARING_PLACE_PUT_SUCCESS';
export const TOWNSHIP_HEARING_PLACE_PUT_ERROR = 'TOWNSHIP_HEARING_PLACE_PUT_ERROR';

export const TOWNSHIP_HEARING_PLACE_POST_REQ = 'TOWNSHIP_HEARING_PLACE_POST_REQ';
export const TOWNSHIP_HEARING_PLACE_POST_SUCCESS = 'TOWNSHIP_HEARING_PLACE_POST_SUCCESS';
export const TOWNSHIP_HEARING_PLACE_POST_ERROR = 'TOWNSHIP_HEARING_PLACE_POST_ERROR';




// Bursar Panel


export const BURSAR_PARKING_PAYMENT_GET_REQ = 'BURSAR_PARKING_PAYMENT_GET_REQ';
export const BURSAR_PARKING_PAYMENT_GET_SUCCESS = 'BURSAR_PARKING_PAYMENT_GET_SUCCESS';
export const BURSAR_PARKING_PAYMENT_GET_ERROR = 'BURSAR_PARKING_PAYMENT_GET_ERROR';

export const BURSAR_PARKING_PAYMENT_PUT_REQ = 'BURSAR_PARKING_PAYMENT_PUT_REQ';
export const BURSAR_PARKING_PAYMENT_PUT_SUCCESS = 'BURSAR_PARKING_PAYMENT_PUT_SUCCESS';
export const BURSAR_PARKING_PAYMENT_PUT_ERROR = 'BURSAR_PARKING_PAYMENT_PUT_ERROR';

export const BURSAR_PARKING_PAYMENT_POST_REQ = 'BURSAR_PARKING_PAYMENT_POST_REQ';
export const BURSAR_PARKING_PAYMENT_POST_SUCCESS = 'BURSAR_PARKING_PAYMENT_POST_SUCCESS';
export const BURSAR_PARKING_PAYMENT_POST_ERROR = 'BURSAR_PARKING_PAYMENT_POST_ERROR';




export const BURSAR_PERMIT_PAYMENT_GET_REQ = 'BURSAR_PERMIT_PAYMENT_GET_REQ';
export const BURSAR_PERMIT_PAYMENT_GET_SUCCESS = 'BURSAR_PERMIT_PAYMENT_GET_SUCCESS';
export const BURSAR_PERMIT_PAYMENT_GET_ERROR = 'BURSAR_PERMIT_PAYMENT_GET_ERROR';

export const BURSAR_PERMIT_PAYMENT_PUT_REQ = 'BURSAR_PERMIT_PAYMENT_PUT_REQ';
export const BURSAR_PERMIT_PAYMENT_PUT_SUCCESS = 'BURSAR_PERMIT_PAYMENT_PUT_SUCCESS';
export const BURSAR_PERMIT_PAYMENT_PUT_ERROR = 'BURSAR_PERMIT_PAYMENT_PUT_ERROR';

export const BURSAR_PERMIT_PAYMENT_POST_REQ = 'BURSAR_PERMIT_PAYMENT_POST_REQ';
export const BURSAR_PERMIT_PAYMENT_POST_SUCCESS = 'BURSAR_PERMIT_PAYMENT_POST_SUCCESS';
export const BURSAR_PERMIT_PAYMENT_POST_ERROR = 'BURSAR_PERMIT_PAYMENT_POST_ERROR';




export const BURSAR_TICKET_PAYMENT_GET_REQ = 'BURSAR_TICKET_PAYMENT_GET_REQ';
export const BURSAR_TICKET_PAYMENT_GET_SUCCESS = 'BURSAR_TICKET_PAYMENT_GET_SUCCESS';
export const BURSAR_TICKET_PAYMENT_GET_ERROR = 'BURSAR_TICKET_PAYMENT_GET_ERROR';

export const BURSAR_TICKET_PAYMENT_PUT_REQ = 'BURSAR_TICKET_PAYMENT_PUT_REQ';
export const BURSAR_TICKET_PAYMENT_PUT_SUCCESS = 'BURSAR_TICKET_PAYMENT_PUT_SUCCESS';
export const BURSAR_TICKET_PAYMENT_PUT_ERROR = 'BURSAR_TICKET_PAYMENT_PUT_ERROR';

export const BURSAR_TICKET_PAYMENT_POST_REQ = 'BURSAR_TICKET_PAYMENT_POST_REQ';
export const BURSAR_TICKET_PAYMENT_POST_SUCCESS = 'BURSAR_TICKET_PAYMENT_POST_SUCCESS';
export const BURSAR_TICKET_PAYMENT_POST_ERROR = 'BURSAR_TICKET_PAYMENT_POST_ERROR';




export const BURSAR_WALLET_PAYMENT_GET_REQ = 'BURSAR_WALLET_PAYMENT_GET_REQ';
export const BURSAR_WALLET_PAYMENT_GET_SUCCESS = 'BURSAR_WALLET_PAYMENT_GET_SUCCESS';
export const BURSAR_WALLET_PAYMENT_GET_ERROR = 'BURSAR_WALLET_PAYMENT_GET_ERROR';

export const BURSAR_WALLET_PAYMENT_PUT_REQ = 'BURSAR_WALLET_PAYMENT_PUT_REQ';
export const BURSAR_WALLET_PAYMENT_PUT_SUCCESS = 'BURSAR_WALLET_PAYMENT_PUT_SUCCESS';
export const BURSAR_WALLET_PAYMENT_PUT_ERROR = 'BURSAR_WALLET_PAYMENT_PUT_ERROR';

export const BURSAR_WALLET_PAYMENT_POST_REQ = 'BURSAR_WALLET_PAYMENT_POST_REQ';
export const BURSAR_WALLET_PAYMENT_POST_SUCCESS = 'BURSAR_WALLET_PAYMENT_POST_SUCCESS';
export const BURSAR_WALLET_PAYMENT_POST_ERROR = 'BURSAR_WALLET_PAYMENT_POST_ERROR';




export const BURSAR_TICKET_RATES_GET_REQ = 'BURSAR_TICKET_RATES_GET_REQ';
export const BURSAR_TICKET_RATES_GET_SUCCESS = 'BURSAR_TICKET_RATES_GET_SUCCESS';
export const BURSAR_TICKET_RATES_GET_ERROR = 'BURSAR_TICKET_RATES_GET_ERROR';

export const BURSAR_TICKET_RATES_PUT_REQ = 'BURSAR_TICKET_RATES_PUT_REQ';
export const BURSAR_TICKET_RATES_PUT_SUCCESS = 'BURSAR_TICKET_RATES_PUT_SUCCESS';
export const BURSAR_TICKET_RATES_PUT_ERROR = 'BURSAR_TICKET_RATES_PUT_ERROR';

export const BURSAR_TICKET_RATES_POST_REQ = 'BURSAR_TICKET_RATES_POST_REQ';
export const BURSAR_TICKET_RATES_POST_SUCCESS = 'BURSAR_TICKET_RATES_POST_SUCCESS';
export const BURSAR_TICKET_RATES_POST_ERROR = 'BURSAR_TICKET_RATES_POST_ERROR';


// Inspector Panel


export const INSPECTOR_PARKING_FIELD_GET_REQ = 'INSPECTOR_PARKING_FIELD_GET_REQ';
export const INSPECTOR_PARKING_FIELD_GET_SUCCESS = 'INSPECTOR_PARKING_FIELD_GET_SUCCESS';
export const INSPECTOR_PARKING_FIELD_GET_ERROR = 'INSPECTOR_PARKING_FIELD_GET_ERROR';

export const INSPECTOR_PARKING_FIELD_PUT_REQ = 'INSPECTOR_PARKING_FIELD_PUT_REQ';
export const INSPECTOR_PARKING_FIELD_PUT_SUCCESS = 'INSPECTOR_PARKING_FIELD_PUT_SUCCESS';
export const INSPECTOR_PARKING_FIELD_PUT_ERROR = 'INSPECTOR_PARKING_FIELD_PUT_ERROR';

export const INSPECTOR_PARKING_FIELD_POST_REQ = 'INSPECTOR_PARKING_FIELD_POST_REQ';
export const INSPECTOR_PARKING_FIELD_POST_SUCCESS = 'INSPECTOR_PARKING_FIELD_POST_SUCCESS';
export const INSPECTOR_PARKING_FIELD_POST_ERROR = 'INSPECTOR_PARKING_FIELD_POST_ERROR';



export const INSPECTOR_PLATE_GET_REQ = 'INSPECTOR_PLATE_GET_REQ';
export const INSPECTOR_PLATE_GET_SUCCESS = 'INSPECTOR_PLATE_GET_SUCCESS';
export const INSPECTOR_PLATE_GET_ERROR = 'INSPECTOR_PLATE_GET_ERROR';

export const INSPECTOR_PLATE_PUT_REQ = 'INSPECTOR_PLATE_PUT_REQ';
export const INSPECTOR_PLATE_PUT_SUCCESS = 'INSPECTOR_PLATE_PUT_SUCCESS';
export const INSPECTOR_PLATE_PUT_ERROR = 'INSPECTOR_PLATE_PUT_ERROR';

export const INSPECTOR_PLATE_POST_REQ = 'INSPECTOR_PLATE_POST_REQ';
export const INSPECTOR_PLATE_POST_SUCCESS = 'INSPECTOR_PLATE_POST_SUCCESS';
export const INSPECTOR_PLATE_POST_ERROR = 'INSPECTOR_PLATE_POST_ERROR';




export const INSPECTOR_TICKET_GET_REQ = 'INSPECTOR_TICKET_GET_REQ';
export const INSPECTOR_TICKET_GET_SUCCESS = 'INSPECTOR_TICKET_GET_SUCCESS';
export const INSPECTOR_TICKET_GET_ERROR = 'INSPECTOR_TICKET_GET_ERROR';

export const INSPECTOR_TICKET_PUT_REQ = 'INSPECTOR_TICKET_PUT_REQ';
export const INSPECTOR_TICKET_PUT_SUCCESS = 'INSPECTOR_TICKET_PUT_SUCCESS';
export const INSPECTOR_TICKET_PUT_ERROR = 'INSPECTOR_TICKET_PUT_ERROR';

export const INSPECTOR_TICKET_POST_REQ = 'INSPECTOR_TICKET_POST_REQ';
export const INSPECTOR_TICKET_POST_SUCCESS = 'INSPECTOR_TICKET_POST_SUCCESS';
export const INSPECTOR_TICKET_POST_ERROR = 'INSPECTOR_TICKET_POST_ERROR';
