export const AUTH_INITIATE = "AUTH_INITIATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const REG_INITIATE = "REG_INITIATE";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAIL = "REG_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const SET_INITIAL_LOCATION = "SET_INITIAL_LOCATION";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";

export const PLATE_ADDITION_INITIATE = "PLATE_ADDITION_INITIATE";
export const PLATE_ADDITION_SUCCESS = "PLATE_ADDITION_SUCCESS";
export const PLATE_ADDITION_FAIL = "PLATE_ADDITION_FAIL";

export const FETCH_VEHICLE_INITIATE = "FETCH_VEHICLE_INITIATE";
export const FETCH_VEHICLE_SUCCESS = "FETCH_VEHICLE_SUCCESS";
export const FETCH_VEHICLE_FAIL = "FETCH_VEHICLE_FAIL";

export const FETCH_VEHICLES_INITIATE = "FETCH_VEHICLES_INITIATE";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_FAIL";

export const FETCH_PARKING_INITIATE = "FETCH_PARKING_INITIATE";
export const FETCH_PARKING_SUCCESS = "FETCH_PARKING_SUCCESS";
export const FETCH_PARKING_FAIL = "FETCH_PARKING_FAIL";

export const FETCH_PARKING_RULES_SUCCESS = "FETCH_PARKING_RULES_SUCCESS";
export const FETCH_PARKING_RULES_FAIL = "FETCH_PARKING_RULES_FAIL";

export const SHOW_FREE_PARKING = "SHOW_FREE_PARKING";
export const SHOW_PAID_PARKING = "SHOW_PAID_PARKING";
export const SHOW_MANAGED_PARKING = "SHOW_MANAGED_PARKING";

export const UPDATE_PLATE = "UPDATE_PLATE";

export const HIDE_SELECTED_PARKING = "HIDE_SELECTED_PARKING";

export const UPDATE_GEOLOCATION = "UPDATE_GEOLOCATION";

export const TOGGLE_FREE_PARKING = "TOGGLE_FREE_PARKING";
export const TOGGLE_PAID_PARKING = "TOGGLE_PAID_PARKING";
export const TOGGLE_MANAGED_PARKING = "TOGGLE_MANAGED_PARKING";

export const SET_PARKING_OPTIONS = "SET_PARKING_OPTIONS";
export const SET_OTHER_LOCATIONS = "SET_OTHER_LOCATIONS";
export const SET_SELECTED_MARKER = "SET_SELECTED_MARKER";
export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";

export const SET_LOCATION_ADDRESS = "SET_LOCATION_ADDRESS";

export const FETCH_PERMITS_INITIATE = "FETCH_PERMITS_INITIATE";
export const FETCH_PERMITS_SUCCESS = "FETCH_PERMITS_SUCCESS";
export const FETCH_PERMITS_FAIL = "FETCH_PERMITS_FAIL";

export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_TICKETS_INITIATE = "FETCH_TICKETS_INITIATE";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAIL = "FETCH_TICKETS_FAIL";

export const SET_MODAL_DATA = "SET_MODAL_DATA";

export const FETCH_LOCATION_INITIATE = "FETCH_LOCATION_INITIATE";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";

export const FETCH_LAT_LNG_INITIATE = "FETCH_LAT_LNG_INITIATE";
export const RECEIVED_LAT_LNG = "RECEIVED_LAT_LNG";
export const RECEIVE_LAT_LNG_FAILED = "RECEIVE_LAT_LNG_FAILED";

export const FETCH_TRANSACTION_INITIATE = "FETCH_TRANSACTION_INITIATE";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAIL = "FETCH_TRANSACTION_FAIL";
export const SET_ADDING_FUNDS = "SET_ADDING_FUNDS";

export const FETCH_WEATHER_INITIATE = "FETCH_WEATHER_INITIATE";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND";

export const FETCH_PLACES_INITIATE = "FETCH_PLACES_INITIATE";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";

export const FETCH_LOCATION_DETAILS_INITIATE = "FETCH_LOCATION_DETAILS_INITIATE";
export const FETCH_LOCATION_DETAILS_SUCCESS = "FETCH_LOCATION_DETAILS_SUCCESS";
export const FETCH_LOCATION_DETAILS_FAIL = "FETCH_LOCATION_DETAILS_FAIL";

export const FETCH_PARKING_LOT_INITIATE = "FETCH_PARKING_LOT_INITIATE";
export const FETCH_PARKING_LOT_SUCCESS = "FETCH_PARKING_LOT_SUCCESS";
export const FETCH_PARKING_LOT_FAIL = "FETCH_PARKING_LOT_FAIL";

export const SELECT_PARKING = "SELECT_PARKING";
export const SET_SELECTED_PLATE = "SET_SELECTED_PLATE";
export const SET_BOOKING_STEP = "SET_BOOKING_STEP";

export const MAKE_BOOKING = "MAKE_BOOKING";

export const INITIATE_GET_CHARGES = "INITIATE_GET_CHARGES";
export const FETCH_CHARGES_SUCCESS = "FETCH_CHARGES_SUCCESS";
export const FETCH_CHARGES_FAIL = "FETCH_CHARGES_FAIL";

export const SET_SELECTED_HOURS = "SET_SELECTED_HOURS";

export const INITIATE_GET_BALANCE = "INITIATE_GET_BALANCE";
export const SET_CURRENT_BALANCE = "SET_CURRENT_BALANCE";
export const SET_PRICE_TO_PAY = "SET_PRICE_TO_PAY";

export const INITIATE_PAYMENT_WITH_WALLET = "INITIATE_PAYMENT_WITH_WALLET";

export const SET_MANAGED_PARKING_TYPE = "SET_MANAGED_PARKING_TYPE";
export const SET_SELECTED_TOWNSHIP = "SET_SELECTED_TOWNSHIP";

export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD";

export const SET_CONFIRMATION_ID = "SET_CONFIRMATION_ID";
export const SET_BOOKING_DATA = "SET_BOOKING_DATA";

export const ENABLE_LOADING = "ENABLE_LOADING";
export const DISABLE_LOADING = "DISABLE_LOADING";

export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const SET_ALREADY_PARKED = "SET_ALREADY_PARKED";

export const SHOW_LOTS = "SHOW_LOTS";
export const SHOW_STREET_VIEW = "SHOW_STREET_VIEW";

export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const REGISTER_VALIDATION_FAILED = "REGISTER_VALIDATION_FAILED";

export const DELETING_VEHICLE = "DELETING_VEHICLE";
export const SET_LOADING = "SET_LOADING";
export const SET_PARKED_CARS_LIST = "SET_PARKED_CARS_LIST";
export const SET_PARKED_CAR_DETAIL = "SET_PARKED_CAR_DETAIL";

export const SET_DIRECTIONS_MODE = "SET_DIRECTIONS_MODE";
export const SET_DIRECTIONS_ORIGIN = "SET_DIRECTIONS_ORIGIN";
export const SET_DIRECTIONS_DESTINATION = "SET_DIRECTIONS_DESTINATION";
export const SET_DIRECTIONS_RESULT = "SET_DIRECTIONS_RESULT";

export const SET_TRAFFIC_ORIGIN = "SET_TRAFFIC_ORIGIN";
export const SET_TRAFFIC_DESTINATION = "SET_TRAFFIC_DESTINATION";
export const SET_TRAFFIC_RESULT = "SET_TRAFFIC_RESULT";

export const LOCATION_ADDITION_INITIATE = "LOCATION_ADDITION_INITIATE";
export const LOCATION_ADDITION_SUCCESS = "LOCATION_ADDITION_SUCCESS";
export const LOCATION_ADDITION_FAIL = "LOCATION_ADDITION_FAIL";

export const DELETING_LOCATION = "DELETING_LOCATION";
export const DELETING_FAIL = "DELETING_FAIL";

export const SEARCH_LOCATION_INITIATE = "SEARCH_LOCATION_INITIATE";
export const SEARCH_LOCATION_SUCCESS = "SEARCH_LOCATION_SUCCESS";
export const SEARCH_LOCATION_FAILS = "SEARCH_LOCATION_FAILS";
